#pragma once

#define LCD_WIDTH  400
#define LCD_HEIGHT 300

#define RLCD_DC_PIN   GPIO_NUM_5
#define RLCD_CS_PIN   GPIO_NUM_40
#define RLCD_SCK_PIN  GPIO_NUM_11
#define RLCD_MOSI_PIN GPIO_NUM_12
#define RLCD_RST_PIN  GPIO_NUM_41
#define RLCD_TE_PIN   GPIO_NUM_6

#define I2S_DSDIN_PIN  GPIO_NUM_8
#define I2S_SCLK_PIN   GPIO_NUM_9
#define I2S_ASDOUT_PIN GPIO_NUM_10
#define I2S_LRCK_PIN   GPIO_NUM_45

#define PA_CTL_PIN GPIO_NUM_46
